server:
  port: 9999
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.125.129:3306/case_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc123


  messages:
    basename: i18n.mymessages   # 国际化资源文件名默认为  messages
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  configuration:   ##下划线转驼峰法配置
    map-underscore-to-camel-case: true
  type-aliases-package: com.abc.case_system.bean

pagehelper:
  helper-dialect: mysql